// # Numbers
// 1. Assign by hand same value to 3 variables in binary, octal and hexadecimal format.
let binary = '1111';
let octal = '0o17';
let hexadecimal = '0xf';

binary = parseInt(binary, 2);
octal = parseInt(octal.slice(2), 8);
hexadecimal = parseInt(hexadecimal, 16);

console.log(binary == octal, octal == hexadecimal, hexadecimal == binary);

// 2. Implement function `extractNumbers` which will leave only numbers in passed string.
let resultString = '';

function extractNumbers(str) {
  for (let char in str) {
    if (isNaN(parseInt(str))){
      str = str.slice(1);
    }
    else {
      resultString += str[0];
      str = str.slice(1);
    }
  }
}

extractNumbers('123abc456fgh');
console.log(resultString);

// 3. Declare a variable with decimal value and convert to binary, octal and hexadecimal.
let decimal = 15;

console.log(`binary value is '${decimal.toString(2)}';
octal value is '${decimal.toString(8)}';
hexadecimal value is '${decimal.toString(16)}'`);


// 4. use `Math.random` to generate random value from `0` to `100`.
function randomBetweenMinAndMax(min, max) {
  return Math.floor(Math.random() * (max - min + 1) + 1);
} 

console.log('Random number: ' + randomBetweenMinAndMax(0, 100));

// # Additional
// 1. Make function which will take a array with numbers as a parameter and
//    calculate average number and round to hundredths.
function average(arr) {
  let sum = 0;
  for (let i = 0; i < arr.length; i++){
    sum += arr[i];
  }
  return Math.round(sum / arr.length);
}

// 2. Generate array to pass to function above with values, and length generated by Math.random.
function randomNumbersArray(length) {
  let arr = [];
  for (i = 0; i < length; i++){
    arr.push(randomBetweenMinAndMax(0, 100));
  }
  return arr;
}

console.log('Average for array of 10 numbers: ' + average(randomNumbersArray(10)));
